import React, { useRef } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import {
  CheckCircle, IndianRupee, ShieldCheck, ArrowLeft,
  Download, Share2, BadgeCheck, Sparkles
} from 'lucide-react';

const SummaryPage = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const summaryRef = useRef(null);

  const {
    cost = { low: 85000, high: 120000 },
    scheme = "Ayushman Bharat PM-JAY",
    schemes = [],
    gap = 0,
    insurance = null,
    procedure = "Surgery"
  } = location.state || {};

  // Calculate gap: max cost minus max scheme coverage
  const maxCoverage = schemes.reduce((acc, s) => acc + s.coverage_inr, 0);
  const estimatedGap = Math.max(0, cost.high - maxCoverage);
  const caseId = `MW-${Math.floor(10000 + Math.random() * 89999)}`;

  const handleDownloadPDF = async () => {
    try {
      // Use window.print as fallback (no external deps needed)
      const printContent = document.getElementById('summary-card').innerHTML;
      const win = window.open('', '', 'width=400,height=700');
      win.document.write(`
        <html>
          <head>
            <title>MediWallet Summary - ${caseId}</title>
            <style>
              body { font-family: Arial, sans-serif; padding: 20px; color: #1e293b; }
              .header { background: #7c3aed; color: white; padding: 24px; border-radius: 12px; text-align: center; margin-bottom: 20px; }
              .card { border: 1px solid #e2e8f0; border-radius: 12px; padding: 16px; margin-bottom: 12px; }
              .label { font-size: 11px; color: #64748b; text-transform: uppercase; font-weight: bold; margin-bottom: 4px; }
              .value { font-size: 18px; font-weight: bold; color: #1e293b; }
              .scheme-badge { background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 8px 12px; margin: 6px 0; }
              .footer { text-align: center; color: #94a3b8; font-size: 11px; margin-top: 20px; }
            </style>
          </head>
          <body>
            <div class="header">
              <h1 style="margin:0;font-size:24px">✅ MediWallet Plan</h1>
              <p style="margin:8px 0 0;font-size:13px;opacity:0.8">Case ID: ${caseId}</p>
            </div>
            <div class="card">
              <div class="label">Procedure</div>
              <div class="value">${procedure.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}</div>
            </div>
            <div class="card">
              <div class="label">Estimated Cost Range</div>
              <div class="value">₹${cost.low.toLocaleString('en-IN')} – ₹${cost.high.toLocaleString('en-IN')}</div>
            </div>
            <div class="card">
              <div class="label">Eligible Government Schemes</div>
              ${(schemes.length ? schemes : [{ name: scheme, coverage_inr: 500000 }]).map(s => `
                <div class="scheme-badge">✓ ${s.name} (Up to ₹${(s.coverage_inr / 100000).toFixed(0)}L)</div>
              `).join('')}
            </div>
            ${insurance ? `
            <div class="card">
              <div class="label">Micro-Insurance</div>
              <div class="value" style="color:#6366f1">₹${insurance.price} – ${insurance.label}</div>
            </div>` : ''}
            <div class="footer">
              Generated by MediWallet AI • Present this at your hospital helpdesk
            </div>
          </body>
        </html>
      `);
      win.document.close();
      win.print();
    } catch (e) {
      alert('Could not generate PDF. Please screenshot this page.');
    }
  };

  const handleShare = async () => {
    const text = `MediWallet Summary\nProcedure: ${procedure}\nEstimated Cost: ₹${cost.low.toLocaleString('en-IN')} – ₹${cost.high.toLocaleString('en-IN')}\nCase ID: ${caseId}`;
    if (navigator.share) {
      await navigator.share({ title: 'MediWallet Summary', text });
    } else {
      navigator.clipboard.writeText(text);
      alert('Summary copied to clipboard!');
    }
  };

  const displaySchemes = schemes.length > 0 ? schemes : [{ name: scheme, coverage_inr: 500000 }];
  const coveragePercent = Math.min(100, Math.round((Math.min(maxCoverage || 500000, cost.high) / cost.high) * 100));

  return (
    <div className="min-h-screen flex flex-col bg-gradient-to-br from-[#0f172a] via-[#1e1b4b] to-[#0f172a]">
      {/* Header */}
      <div className="px-4 py-4 flex items-center gap-3 border-b border-white/10">
        <button
          onClick={() => navigate(-1)}
          className="w-8 h-8 flex items-center justify-center text-white/60 hover:text-white transition-colors"
        >
          <ArrowLeft size={20} />
        </button>
        <h2 className="text-white font-bold flex-1">Treatment Summary</h2>
        <button
          onClick={handleShare}
          className="flex items-center gap-1 bg-white/5 border border-white/10 text-white/60 text-xs px-3 py-1.5 rounded-full hover:bg-white/10 transition-all"
        >
          <Share2 size={12} /> Share
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-4 space-y-4" id="summary-card" ref={summaryRef}>
        {/* Hero Banner */}
        <div className="bg-gradient-to-br from-purple-600 via-indigo-600 to-purple-800 rounded-3xl p-6 text-center shadow-2xl shadow-purple-500/20 relative overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-br from-white/5 to-transparent rounded-3xl" />
          <div className="w-16 h-16 bg-white/15 rounded-2xl flex items-center justify-center mx-auto mb-3 backdrop-blur border border-white/20">
            <CheckCircle size={36} className="text-green-300" />
          </div>
          <h2 className="text-2xl font-black text-white">Plan Ready! 🎉</h2>
          <p className="text-purple-200 text-sm mt-1">Case ID: <span className="font-mono font-bold">{caseId}</span></p>
          <div className="mt-3 inline-flex items-center gap-1 bg-white/10 border border-white/20 rounded-full px-3 py-1">
            <Sparkles size={12} className="text-yellow-300" />
            <span className="text-white/80 text-xs font-semibold">
              {procedure.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}
            </span>
          </div>
        </div>

        {/* Cost Card */}
        <div className="bg-white/8 backdrop-blur border border-white/10 rounded-2xl p-5">
          <div className="flex items-center gap-2 mb-3">
            <div className="w-8 h-8 bg-orange-500/20 rounded-xl flex items-center justify-center">
              <IndianRupee size={16} className="text-orange-300" />
            </div>
            <p className="text-white/50 text-xs font-bold uppercase tracking-wider">Estimated Cost</p>
          </div>
          <p className="text-3xl font-black text-white">
            ₹{cost.low.toLocaleString('en-IN')}
            <span className="text-white/30 font-normal text-xl"> – </span>
            ₹{cost.high.toLocaleString('en-IN')}
          </p>
          <p className="text-white/40 text-xs mt-1">Private hospital, approximate range</p>

          {/* Coverage bar */}
          <div className="mt-4">
            <div className="flex justify-between text-xs text-white/50 mb-1">
              <span>Govt. scheme coverage</span>
              <span className="text-teal-300 font-bold">{coveragePercent}% covered</span>
            </div>
            <div className="h-2 bg-white/10 rounded-full overflow-hidden">
              <div
                className="h-full bg-gradient-to-r from-teal-400 to-teal-500 rounded-full transition-all duration-1000"
                style={{ width: `${coveragePercent}%` }}
              />
            </div>
          </div>
        </div>

        {/* Schemes */}
        <div className="bg-white/8 backdrop-blur border border-white/10 rounded-2xl p-5">
          <div className="flex items-center gap-2 mb-3">
            <div className="w-8 h-8 bg-teal-500/20 rounded-xl flex items-center justify-center">
              <ShieldCheck size={16} className="text-teal-300" />
            </div>
            <p className="text-white/50 text-xs font-bold uppercase tracking-wider">Government Schemes</p>
          </div>
          {displaySchemes.map((s, i) => (
            <div key={i} className="flex items-center justify-between p-3 bg-teal-500/10 border border-teal-400/20 rounded-xl mb-2">
              <div className="flex items-center gap-2">
                <BadgeCheck size={16} className="text-teal-400 shrink-0" />
                <div>
                  <p className="text-white text-sm font-semibold">{s.name}</p>
                  {s.description && <p className="text-white/40 text-xs mt-0.5 line-clamp-1">{s.description}</p>}
                </div>
              </div>
              <div className="text-right shrink-0 ml-2">
                <p className="text-teal-300 text-sm font-bold">₹{(s.coverage_inr / 100000).toFixed(0)}L</p>
                <p className="text-white/30 text-xs">max</p>
              </div>
            </div>
          ))}
        </div>

        {/* Gap Insurance */}
        {insurance ? (
          <div className="bg-gradient-to-br from-indigo-500/20 to-purple-500/10 border border-indigo-400/20 rounded-2xl p-5">
            <div className="flex items-center gap-2 mb-2">
              <div className="w-8 h-8 bg-indigo-500/20 rounded-xl flex items-center justify-center">
                <span className="text-base">🛡️</span>
              </div>
              <p className="text-white/50 text-xs font-bold uppercase tracking-wider">Micro-Insurance Active</p>
            </div>
            <div className="flex items-center justify-between">
              <div>
                <p className="text-white font-bold">{insurance.label}</p>
                <p className="text-indigo-300 text-sm">Covers gap beyond scheme limits</p>
              </div>
              <div className="text-right">
                <p className="text-indigo-300 font-black text-xl">₹{insurance.price}</p>
                <p className="text-white/30 text-xs">paid ✓</p>
              </div>
            </div>
          </div>
        ) : estimatedGap > 0 ? (
          <div className="bg-orange-500/10 border border-orange-400/20 rounded-2xl p-4 flex items-center justify-between">
            <div>
              <p className="text-orange-300 font-semibold text-sm">Out-of-pocket gap</p>
              <p className="text-white/50 text-xs mt-0.5">After scheme coverage applied</p>
            </div>
            <p className="text-orange-300 font-black text-lg">
              ~₹{estimatedGap.toLocaleString('en-IN')}
            </p>
          </div>
        ) : null}

        {/* Hospital Tip */}
        <div className="bg-white/5 border border-white/8 rounded-2xl p-4 flex items-start gap-3">
          <span className="text-2xl">💡</span>
          <div>
            <p className="text-white font-semibold text-sm">Show this at the hospital</p>
            <p className="text-white/40 text-xs mt-1">
              Present this summary at the hospital's insurance helpdesk to initiate your claim. Bring your Aadhaar card for verification.
            </p>
          </div>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="p-4 border-t border-white/10 space-y-3 bg-[#0f172a]/80 backdrop-blur">
        <button
          onClick={handleDownloadPDF}
          className="w-full py-4 bg-gradient-to-r from-purple-500 to-indigo-600 text-white font-bold rounded-2xl shadow-lg shadow-purple-500/30 hover:shadow-purple-500/50 hover:scale-[1.02] active:scale-[0.98] transition-all flex items-center justify-center gap-2"
        >
          <Download size={18} /> Download PDF Summary
        </button>
        <button
          onClick={() => navigate('/chat', { state: location.state })}
          className="w-full py-3 bg-white/5 border border-white/10 text-white/60 font-semibold rounded-2xl hover:bg-white/10 transition-all"
        >
          Back to Chat
        </button>
      </div>
    </div>
  );
};

export default SummaryPage;
